version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: teamtasks-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: teamtasks
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
