spring:
  profiles:
    active: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/fake_database
    username: fake_user
    password: fake_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

logging:
  level:
    root: INFO
    com.briancabrera: DEBUG
